version: '2'
services:
  nfs:
    image: nfs
    build:
      context: .
      dockerfile: DockerNFS
    container_name: nfs
    privileged: true
    hostname: nfs
    tty: true
    command: /exports/data
    networks:
      net:
        ipv4_address: 10.5.0.3
  r:
    image: rserver
    build:
      context: .
      dockerfile: DockerR
    container_name: rserver
    privileged: true
    shm_size: 25G
    stdin_open: true
    depends_on:
      - "nfs"
    command: ["/bin/bash", "-c", "/wait_showmount.sh"]
    networks:
      net:
        ipv4_address: 10.5.0.2
    tty: true

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
